# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Route.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRoute.proto\x12\x08tutorial\"2\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0c\n\x04long\x18\x02 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x02\"A\n\nRoutePoint\x12$\n\x08location\x18\x01 \x01(\x0b\x32\x12.tutorial.Location\x12\r\n\x05speed\x18\x02 \x01(\x02\"5\n\nRouteArray\x12\'\n\twaypoints\x18\x01 \x03(\x0b\x32\x14.tutorial.RoutePointB3\n/com.dji.sdk.sample.tigersalvage.proto.generatedP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Route_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n/com.dji.sdk.sample.tigersalvage.proto.generatedP\001'
  _LOCATION._serialized_start=25
  _LOCATION._serialized_end=75
  _ROUTEPOINT._serialized_start=77
  _ROUTEPOINT._serialized_end=142
  _ROUTEARRAY._serialized_start=144
  _ROUTEARRAY._serialized_end=197
# @@protoc_insertion_point(module_scope)
